apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-required-node-affinity
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: device
                operator: In
                values:
                - gpu
      containers:
      - name: nginx
        image: nginx