- name: Setup environment
  hosts: all
  become: true

  vars_files:
    - vars/consul.yml
    - vars/nomad.yml
    - vars/general.yml

  tasks:
    - include_role:
        name: general
        tasks_from: install
