apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-preferred-node-affinity
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: device 
                operator: In
                values:
                - gpu
          - weight: 20
            preference:
              matchExpressions:
              - key: device
                operator: In
                values:
                - cpu
      containers:
      - name: nginx
        image: nginx