apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: websites.extensions.example.com
spec:
  scope: Namespaced # either Namespaced or Cluster
  group: extensions.example.com # group name to use for REST API: /apis/<group>/<version>
  versions:
    - name: v1
      served: true # Each version can be enabled/disabled by Served flag.
      storage: true # One and only one version must be marked as the storage version.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRepo:
                  type: string
  names:
    kind: Website # kind is normally the CamelCased singular type. Your resource manifests use this.
    singular: website # singular name to be used as an alias on the CLI and for display
    plural: websites # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    shortNames: # shortNames allow shorter string to match your resource on the CLI
    - gitrp