apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: default
data:
  db_host: mysql-service
---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: busybox
        command: ['/bin/sh', '-c', "env"]
        envFrom:
        - configMapRef:
            name: myapp-config
        - secretRef:
            name: myapp-secret