apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  db_host: mysql-service
---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: busybox
        command: ['/bin/echo', "$(MYSQL_USER) $(MYSQL_PASSWORD) $(MYSQL_SERVER)"]
        env:
        - name: MYSQL_SERVER 
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: db_host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: password