version: '3'

services:
  proxy:
    image: nginx:alpine
    networks:
      - site1
      - site2
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./404.html:/var/www/html/404.html
      - ./includes:/etc/nginx/includes

networks:
  site1:
    external:
      name: site1_default
  site2:
    external:
      name: site2_default