version: '3.8'

networks:
 mysqlnet:
  driver: bridge
services:
 web:
  build:
   context: .
  networks:
  - mysqlnet
  ports:
  - 9000:9000
  container_name: rest-server
  volumes:
  - ./:/app

 mysqldb:
  image: mysql
  networks:
  - mysqlnet
  ports:
  - 3306:3306
  container_name: mysqldb
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
