- hosts: master
  become_user: vagrant
  gather_facts: no
  tasks:
    - name: get join command
      shell: sudo kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"

- hosts: workers
  become_user: vagrant
  tasks:
    - name: join worker to cluster
      shell: sudo {{ hostvars['master'].join_command }} >> join_worker.txt
      args:
        chdir: $HOME