hosts = {
    "n1" => "192.168.56.10",
    "n2" => "192.168.56.11",
    "n3" => "192.168.56.12"
}

Vagrant.configure("2") do |config|

    config.ssh.insert_key = false
    config.ssh.forward_agent = true

    check_guest_additions = false
    functional_vboxsf = false

    config.vm.box = "bento/ubuntu-16.04"

    hosts.each do |name, ip|
        config.vm.define name do |machine|
            machine.vm.network :private_network, ip: ip
            machine.vm.provider "virtualbox" do |v|
                v.name = name
                v.memory = 1024
                v.cpus = 1
            machine.vm.provision "shell", inline: "swapoff -a"
            end
        end
    end
end
