---
- hosts: all
  become: yes
  vars:
    user: "{{ ansible_env.SUDO_USER }}"
  tasks:
    - name: Create root file
      file:
        path: /tmp/file_of_root
        state: touch

    - name: Create {{ user }} file
      become_user: "{{ user }}"
      file:
        path: /tmp/file_of_{{ user }}
        state: touch

