- hosts: master-1
  become_user: vagrant
  gather_facts: no
  tasks:
    - name: reset cluster
      shell: |
        sudo kubeadm reset --force
        sudo rm -rf .kube
      args:
        chdir: $HOME

    - name: pull kube image
      shell: sudo kubeadm config images pull --kubernetes-version v1.23.0
      args:
        chdir: $HOME

    - name: initialize the cluster
      shell: sudo kubeadm init --control-plane-endpoint "192.168.56.14:6443" --apiserver-advertise-address=192.168.56.10 --pod-network-cidr=10.244.0.0/16 --upload-certs --ignore-preflight-errors=all > init_cluster.txt
      args:
        chdir: $HOME

    - name: create .kube directory
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: download network plugin
      get_url:
        url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        dest: $HOME

    - name: install pod network
      shell: sudo kubectl apply -f kube-flannel.yml
      args:
        chdir: $HOME

    - name: get certificate key
      shell: cat init_cluster.txt | sed -n "s/.*--certificate-key\s\(\w*\)/\1/p"
      register: certificate_key_raw

    - name: set certificate key to variable
      set_fact:
        certificate_key: "{{ certificate_key_raw.stdout }}"

    - name: get join command
      shell: sudo kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout }}"


- hosts: master-2
  become_user: vagrant
  tasks:
    - name: reset cluster
      shell: |
        sudo kubeadm reset --force
        sudo rm -rf .kube
      args:
        chdir: $HOME

    - name: pull kube image
      shell: sudo kubeadm config images pull --kubernetes-version v1.23.0
      args:
        chdir: $HOME

    - name: join master to cluster
      shell: sudo {{ hostvars['master-1'].join_command }} --control-plane --certificate-key {{ hostvars['master-1'].certificate_key }} --apiserver-advertise-address=192.168.56.11 --ignore-preflight-errors=all > join_master.txt
      args:
        chdir: $HOME

    - name: create .kube directory
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config


- hosts: workers
  become_user: vagrant
  tasks:
    - name: reset cluster
      shell: |
        sudo kubeadm reset --force
        sudo rm -rf .kube
      args:
        chdir: $HOME

    - name: join worker to cluster
      shell: sudo {{ hostvars['master-1'].join_command }} > join_worker.txt
      args:
        chdir: $HOME
