apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-with-toleration
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 5 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      tolerations:
      - key: node-type
        operator: Equal
        value: production
        effect: NoSchedule